#!/bin/bash

# Check if the PYFILE environment variable is set
if [ -z "$PYFILE" ]; then
    exit 1
fi

# Check if the specified Python file exists
if [ ! -f "$PYFILE" ]; then
    exit 1
fi

python3 "$PYFILE"
